name: ant_maze
qdax_name: ant_maze
backend: 
version: v1
reward_type: final

episode_length: 1000
policy_hidden_layer_size: [128, 128]
healthy_z_range: [0.2, 5]
exclude_current_positions_from_observation: true
use_contact_forces: false


# passive archive settings
min_bd: -5
max_bd: 40
grid_shape: [40, 40]
num_init_cvt_samples: 50000
num_centroids: 1024

task: # active archive settings
  bd_extractor: "xy_pos"
  grid_shape: [40, 40]
  min_bd: -5
  max_bd: 40
  num_init_cvt_samples: 50000
  num_centroids: 1024
  num_descriptors: 2

# max/min task fitness values for consistent plotting
vmax: 0
vmin: -57

observation_extraction:
  subsample: true
  sampling_freq: 10
  observation_option: "sensory_data" # options: "sensory_data" or "images"
  normalize_obs: true
  max_obs_size: 30
