name: map_elites_baseline
defaults: 
  - hydra: default # load default hydra settings
  - wandb: default # load default wandb settings
  - env: kheperax # load environment settings
  - _self_

seed: 42

# QD settings
batch_size: 512
num_iterations: 2000
num_total_steps: 1_000_000 # num_total_evals * episode_length

metrics_log_period: 5
me_repertoire: true

# Emitter settings
iso_sigma: 0.005
line_sigma: 0.05

# Extinction settings
extinction: false
extinction_freq: 10
remaining_prop: 0.05

env_params:
  kheperax:
    iso_sigma: 0.2
    line_sigma: 0
  ant_maze:
    iso_sigma: 0.005
    line_sigma: 0.05
  walker:
    iso_sigma: 0.005
    line_sigma: 0.05
  half_cheetah:
    iso_sigma: 0.005
    line_sigma: 0.05

wandb: 
  group: ${env.name}
  tags: ['${name}', '${env.name}']