name: kheperax
reward_type: final

episode_length: 200
resolution: [64, 64]
policy_hidden_layer_size: [5,]
map_name: "standard"
lasers_return_minus_one_if_out_of_range: false
std_noise_wheel_velocities: 0.
std_noise_sensor_measures: 0.
action_scale: 0.025


# active archive settings
grid_shape: [40, 40]
min_bd: 0
max_bd: 1
num_init_cvt_samples: 50000
num_centroids: 1024

task: # passive archive settings
  bd_extractor: "xy_pos"
  grid_shape: [40, 40]
  min_bd: 0
  max_bd: 1
  num_init_cvt_samples: 50000
  num_centroids: 1024
  num_descriptors: 2

# max/min task fitness values for consistent plotting
vmax: 0
vmin: -124

observation_extraction:
  subsample: true
  sampling_freq: 4
  observation_option: "sensory_data" # options: "sensory_data" or "images"
  normalize_obs: true
  max_obs_size: 25